### ISSUE TITLE
Error @ /#/dashboard

### ISSUE THREAD

**Issue by alanlichen** [ericellb/React-Discord-Clone#20]
The dashboard is just infinitely looping at this:
![image](https://user-images.githubusercontent.com/40917647/123352880-1b101380-d515-11eb-93a8-136736bc55f2.png)

I decided to take a look at the inspect console, and I found some errors:
![image](https://user-images.githubusercontent.com/40917647/123352953-4430a400-d515-11eb-939a-b6a760ee0548.png)

**Comment by alanlichen** [comment]
Was this fixed? I didn't see a commit. Would be very appreciated if you fixed it.
I was about to tinker with it myself, but then I realized you closed the rest of the open issues. Any reason why?

**Comment by ericellb** [comment]
This is only the frontend for the Discord Clone, it also requires a backend to connect to in order to properly host the project.

I closed this since this project is not currently being maintained. It was originally posted just for show since I was hosting it and a lot of people asked to see the code.

If you are interested in getting it working you'll need to also host the backend which is on my github in order for it to work.

**Comment by alanlichen** [comment]
Thanks! Personally, I would add a small warning along with the unmaintained part, saying that this uses bad practices. This way, people don't copy the password things and use it for an actual production thing.
